### save a user
POST http://localhost:8081/api/users
Content-Type: application/json

{
  "fullName": "Reza Mirzaei",
  "username": "rezamirzaei",
  "password": "abcd1234",
  "addressDto": {
    "city": "Ilam",
    "street": "Edalat",
    "alley": "Adl 3",
    "floor": 2,
    "number": 1,
    "postalCode": "2222222222"
  }
}

### get a single user
GET http://localhost:8081/api/users/1
### get a single user with chache mechanism, it will sleep for 20 secs in the first run
GET http://localhost:8081/api/users/1/cached
### does not exists
GET http://localhost:8081/api/users/10
### get list of users
GET http://localhost:8081/api/users
###